name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install dotnet-format
        run: dotnet tool install -g dotnet-format

      - name: Add dotnet-format problem matcher
        uses: xt0rted/dotnet-format-problem-matcher@v1

      - name: Restore dotnet tools
        uses: xt0rted/dotnet-tool-restore@v1

      - name: Run dotnet format
        uses: xt0rted/dotnet-format@v1.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  infer:
    runs-on: ubuntu-latest
    steps:
      - name: Run Infer#      
        uses: microsoft/infersharpaction@v0.2
        id: runinfersharp
        with:
          binary-path: 'src/'
      - name: Infer# analysis results
        run: echo "${{ steps.runinfersharp.outputs.results }}"  

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal
