name: Pack

on:
  push:
    tags:
      - 'v*.*.*'

jobs:

  print-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}

  pack:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100

    - name: Install dotnet tool
      run: dotnet tool install -g dotnetCampus.TagToVersion

    - name: Set tag to version
      run: dotnet TagToVersion -t ${GITHUB_REF} -f Directory.Build.props

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Pack
      env:
        PROJECT_NAME: DotnetDocument.Tools
        PACKAGE_ID: dotnet-document
      run: |
        dotnet pack -v normal -c Release --no-restore \
          --include-symbols --include-source \
          -p:PackageID=$PACKAGE_ID \
          src/$PROJECT_NAME/$PROJECT_NAME.*proj
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: nupkg
        path: ./src/DotnetDocument.Tools/nupkg/*.nupkg
