name: Release

on:
  push:
    tags:
      - '*.*.*'

env:
  DOTNET_VERSION: 5.0.100
  PACKAGE_ID: dotnet-document
  NUPKG_PATH: ./src/DotnetDocument.Tools/nupkg/*.nupkg
  PROJECT_PATH: src/DotnetDocument.Tools/DotnetDocument.Tools.csproj

jobs:

  test:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set RELEASE_VERSION env var
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Print RELEASE_VERSION
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}
